/**
 * Tailwind utilities for the NFC walkthrough.
 * The semantic hook at the start of each value scopes arbitrary descendant variants.
 */
const styles = {
  activeStep: `tw-components-landing-nfc-demo-activeStep [border-color:rgb(111_179_255_/_20%)]! [background:rgb(255_255_255_/_7.5%)] [color:white] [&_.tw-components-landing-nfc-demo-stepNumber]:[background:var(--blue)] [&_.tw-components-landing-nfc-demo-stepNumber]:[box-shadow:0_0_28px_rgb(20_110_245_/_35%)] [&_.tw-components-landing-nfc-demo-stepNumber]:[color:white] [&_.tw-components-landing-nfc-demo-stepDescription]:[color:#b7c7d8]`,
  browser: `tw-components-landing-nfc-demo-browser [position:absolute] [z-index:6] [inset:5px] [padding:48px_14px_16px] [transform:translateY(16px)] [border-radius:31px] [opacity:0] [background:#f5f8fb] [color:var(--ink)] [transition:opacity_550ms_ease,_transform_550ms_ease] max-[600px]:[border-radius:25px]`,
  browserActions: `tw-components-landing-nfc-demo-browserActions [display:grid] [gap:8px] [margin-top:10px] [grid-template-columns:1fr_1fr] [&_span]:[display:grid] [&_span]:[height:54px] [&_span]:[place-items:center] [&_span]:[border:1px_solid_#e0e7ee] [&_span]:[border-radius:15px] [&_span]:[background:white] [&_span]:[font-size:0.56rem] [&_span]:[font-weight:850]`,
  browserBottom: `tw-components-landing-nfc-demo-browserBottom [height:64px] [margin-top:8px] [padding:13px] [border-radius:15px] [background:#e9f3ff] [color:#3e5f83] [font-size:0.56rem] [line-height:1.5]`,
  browserCover: `tw-components-landing-nfc-demo-browserCover [position:relative] [height:125px] [overflow:hidden] [margin-top:12px] [padding:18px] [border-radius:19px] [background:linear-gradient(135deg,_#071321,_#164c8d)] [color:white] [&::after]:[position:absolute] [&::after]:[right:-4px] [&::after]:[bottom:-24px] [&::after]:[color:rgb(255_255_255_/_8%)] [&::after]:[content:'K2'] [&::after]:[font-size:4.6rem] [&::after]:[font-weight:950] [&_small]:[color:#83bfff] [&_small]:[font-size:0.58rem] [&_h3]:[margin:24px_0_3px] [&_h3]:[font-size:1.18rem] [&_span]:[color:#bdd7ff] [&_span]:[font-size:0.56rem]`,
  browserPill: `tw-components-landing-nfc-demo-browserPill [display:flex] [height:32px] [align-items:center] [justify-content:center] [border:1px_solid_#dae3ec] [border-radius:12px] [background:white] [color:#68788b] [font-size:0.56rem]`,
  caption: `tw-components-landing-nfc-demo-caption [position:absolute] [top:35px] [left:38px] [color:#718aa4] [font-size:0.68rem] [font-weight:850] [letter-spacing:0.12em] [text-transform:uppercase] max-[600px]:[top:24px] max-[600px]:[left:22px]`,
  controls: `tw-components-landing-nfc-demo-controls [display:flex] [flex-direction:column] [gap:9px] [padding:26px] [border-right:1px_solid_rgb(255_255_255_/_8%)] max-[900px]:[display:grid] max-[900px]:[border-right:0] max-[900px]:[border-bottom:1px_solid_rgb(255_255_255_/_8%)] max-[900px]:[grid-template-columns:1fr_1fr] max-[600px]:[padding:12px] max-[600px]:[grid-template-columns:1fr]`,
  date: `tw-components-landing-nfc-demo-date [position:absolute] [top:112px] [right:0] [left:0] [color:#b9c8d8] [font-size:0.68rem] [text-align:center] max-[600px]:[top:97px]`,
  demo: `tw-components-landing-nfc-demo-demo [overflow:hidden] [margin-top:26px] [border:1px_solid_rgb(255_255_255_/_6%)] [border-radius:38px] [background:linear-gradient(145deg,_#071321,_#0a1a2c)] [box-shadow:0_34px_90px_rgb(7_17_31_/_20%)] [color:white] [&[data-step='2']_.tw-components-landing-nfc-demo-phone]:[transform:translateX(-12px)_translateY(42px)_rotate(-2deg)] [&[data-step='2']_.tw-components-landing-nfc-demo-rays]:[opacity:1] [&[data-step='3']_.tw-components-landing-nfc-demo-rays]:[opacity:1] [&[data-step='3']_.tw-components-landing-nfc-demo-phone]:[transform:translateX(-25px)_translateY(25px)_rotate(0deg)] [&[data-step='3']_.tw-components-landing-nfc-demo-notice]:[transform:none] [&[data-step='3']_.tw-components-landing-nfc-demo-notice]:[opacity:1] [&[data-step='4']_.tw-components-landing-nfc-demo-notice]:[transform:translateY(-10px)] [&[data-step='4']_.tw-components-landing-nfc-demo-notice]:[opacity:0] [&[data-step='4']_.tw-components-landing-nfc-demo-phone]:[transform:translateX(-34px)_translateY(10px)_rotate(0deg)] [&[data-step='4']_.tw-components-landing-nfc-demo-browser]:[transform:none] [&[data-step='4']_.tw-components-landing-nfc-demo-browser]:[opacity:1] max-[600px]:[border-radius:28px] max-[600px]:[&[data-step='2']_.tw-components-landing-nfc-demo-phone]:[transform:translateX(-24px)_translateY(40px)_rotate(-2deg)]`,
  deskShadow: `tw-components-landing-nfc-demo-deskShadow [position:absolute] [bottom:54px] [left:14%] [width:72%] [height:58px] [border-radius:50%] [background:rgb(0_0_0_/_36%)] [filter:blur(22px)]`,
  grid: `tw-components-landing-nfc-demo-grid [display:grid] [min-height:520px] [grid-template-columns:0.76fr_1.24fr] max-[900px]:[grid-template-columns:1fr]`,
  header: `tw-components-landing-nfc-demo-header [display:flex] [align-items:end] [justify-content:space-between] [gap:30px] [padding:34px_36px_22px] [border-bottom:1px_solid_rgb(255_255_255_/_8%)] [&_small]:[color:#6fb3ff] [&_small]:[font-size:0.7rem] [&_small]:[font-weight:850] [&_small]:[letter-spacing:0.14em] [&_small]:[text-transform:uppercase] [&_h2]:[margin:10px_0_0] [&_h2]:[font-size:clamp(1.9rem,_4vw,_3rem)] [&_h2]:[letter-spacing:-0.05em] [&_h2]:[line-height:1] [&_p]:[max-width:470px] [&_p]:[margin:0] [&_p]:[color:#a8bacd] [&_p]:[font-size:0.88rem] [&_p]:[line-height:1.65] max-[900px]:[align-items:start] max-[600px]:[display:block] max-[600px]:[padding:28px_22px_18px] max-[600px]:[&_p]:[margin-top:16px]`,
  notice: `tw-components-landing-nfc-demo-notice [position:absolute] [z-index:7] [top:152px] [right:13px] [left:13px] [display:flex] [align-items:center] [gap:10px] [padding:13px] [transform:translateY(-8px)_scale(0.96)] [border-radius:18px] [opacity:0] [background:rgb(247_250_253_/_94%)] [box-shadow:0_12px_30px_rgb(0_0_0_/_28%)] [color:var(--ink)] [transition:opacity_450ms_ease,_transform_450ms_ease] [&_b]:[display:block] [&_span]:[display:block] [&_b]:[font-size:0.75rem] [&_span]:[margin-top:2px] [&_span]:[color:#718093] [&_span]:[font-size:0.61rem] max-[600px]:[top:130px] max-[600px]:[padding:10px]`,
  noticeIcon: `tw-components-landing-nfc-demo-noticeIcon [display:grid] [width:37px] [height:37px] [flex:none] [place-items:center] [border-radius:12px] [background:var(--deep)] [color:white] [font-size:0.7rem] [font-weight:900]`,
  phone: `tw-components-landing-nfc-demo-phone [position:absolute] [z-index:5] [top:56px] [right:9%] [width:228px] [height:448px] [overflow:hidden] [transform:translateX(78px)_rotate(5deg)] [border:7px_solid_#060c14] [border-radius:42px] [background:#02060c] [box-shadow:0_36px_70px_rgb(0_0_0_/_40%)] [transition:transform_750ms_cubic-bezier(0.2,_0.75,_0.2,_1)] [&::before]:[position:absolute] [&::before]:[z-index:8] [&::before]:[top:10px] [&::before]:[left:50%] [&::before]:[width:76px] [&::before]:[height:22px] [&::before]:[transform:translateX(-50%)] [&::before]:[border-radius:20px] [&::before]:[background:#000] [&::before]:[content:''] max-[600px]:[top:68px] max-[600px]:[right:4%] max-[600px]:[width:182px] max-[600px]:[height:360px] max-[600px]:[border-radius:34px] max-[370px]:[right:-2%]`,
  rays: `tw-components-landing-nfc-demo-rays [position:absolute] [z-index:4] [top:39%] [left:36%] [width:112px] [height:112px] [opacity:0.08] [transition:opacity_450ms_ease] [&_span]:[position:absolute] [&_span]:[inset:0] [&_span]:[border:2px_solid_#4aa5ff] [&_span]:[border-radius:50%] [&_span]:[animation:demoPulse_1.35s_infinite] [&_span:nth-child(2)]:[inset:-24px] [&_span:nth-child(2)]:[animation-delay:200ms] [&_span:nth-child(3)]:[inset:-48px] [&_span:nth-child(3)]:[animation-delay:400ms] max-[600px]:[top:42%] max-[600px]:[left:30%] max-[600px]:[transform:scale(0.7)]`,
  replay: `tw-components-landing-nfc-demo-replay [min-height:44px] [margin-top:auto] [padding:12px_15px] [border:1px_solid_rgb(255_255_255_/_12%)] [border-radius:16px] [background:transparent] [color:#d7e4f1] [cursor:pointer] [font-size:0.75rem] [font-weight:800] [&:hover]:[background:rgb(255_255_255_/_6%)] max-[900px]:[grid-column:1_/_-1]`,
  scene: `tw-components-landing-nfc-demo-scene [position:relative] [min-height:520px] [overflow:hidden] [background:radial-gradient(circle_at_64%_44%,_rgb(34_116_224_/_19%),_transparent_34%),_linear-gradient(160deg,_rgb(255_255_255_/_2.5%),_transparent_45%)] [&::after]:[position:absolute] [&::after]:[right:0] [&::after]:[bottom:84px] [&::after]:[left:0] [&::after]:[height:1px] [&::after]:[background:linear-gradient(90deg,_transparent,_rgb(111_179_255_/_25%),_transparent)] [&::after]:[content:''] max-[600px]:[min-height:455px]`,
  status: `tw-components-landing-nfc-demo-status [position:absolute] [top:58px] [left:38px] [max-width:330px] [font-size:1.18rem] [font-weight:850] [letter-spacing:-0.02em] max-[600px]:[top:45px] max-[600px]:[left:22px] max-[600px]:[max-width:220px] max-[600px]:[font-size:0.94rem]`,
  step: `tw-components-landing-nfc-demo-step [display:grid] [padding:18px] [border:1px_solid_transparent] [border-radius:20px] [appearance:none] [background:transparent] [color:#91a4b9] [cursor:pointer] [gap:12px] [grid-template-columns:42px_1fr] [text-align:left] [transition:color_250ms_ease,_background_250ms_ease,_border-color_250ms_ease] [&:hover]:[background:rgb(255_255_255_/_4%)] [&_b]:[display:block] [&_b]:[margin:2px_0_5px] [&_b]:[font-size:0.94rem] max-[600px]:[padding:13px_14px]`,
  stepDescription: `tw-components-landing-nfc-demo-stepDescription [display:block] [color:#8196ab] [font-size:0.75rem] [line-height:1.45]`,
  stepNumber: `tw-components-landing-nfc-demo-stepNumber [display:grid] [width:42px] [height:42px] [place-items:center] [border-radius:14px] [background:rgb(255_255_255_/_6%)] [color:#6fb3ff] [font-size:0.68rem] [font-weight:900]`,
  tabList: `tw-components-landing-nfc-demo-tabList [display:contents]`,
  tag: `tw-components-landing-nfc-demo-tag [position:absolute] [z-index:3] [bottom:118px] [left:10%] [width:260px] [height:162px] [padding:24px] [transform:rotate(-7deg)] [border:1px_solid_rgb(255_255_255_/_12%)] [border-radius:30px] [background:linear-gradient(145deg,_#101d2d,_#050c15)] [box-shadow:0_28px_54px_rgb(0_0_0_/_28%)] max-[600px]:[bottom:96px] max-[600px]:[left:5%] max-[600px]:[width:205px] max-[600px]:[height:132px] max-[600px]:[padding:18px] max-[600px]:[border-radius:24px] max-[370px]:[left:1%] max-[370px]:[width:190px]`,
  tagBrand: `tw-components-landing-nfc-demo-tagBrand [font-size:1.42rem] [font-weight:900] [letter-spacing:-0.05em] [&_b]:[color:#55a7ff]`,
  tagCopy: `tw-components-landing-nfc-demo-tagCopy [position:absolute] [bottom:22px] [left:24px] [color:#afc3dc] [font-size:0.7rem] [line-height:1.5] [&_b]:[color:white] max-[600px]:[bottom:16px] max-[600px]:[left:18px] max-[600px]:[font-size:0.56rem]`,
  tagIcon: `tw-components-landing-nfc-demo-tagIcon [position:absolute] [top:22px] [right:22px] [display:grid] [width:42px] [height:42px] [place-items:center] [border:1px_solid_rgb(255_255_255_/_18%)] [border-radius:50%] [color:#6fb3ff] max-[600px]:[top:16px] max-[600px]:[right:16px] max-[600px]:[width:36px] max-[600px]:[height:36px]`,
  time: `tw-components-landing-nfc-demo-time [position:absolute] [top:65px] [right:0] [left:0] [font-size:2.55rem] [font-weight:300] [letter-spacing:-0.04em] [text-align:center] max-[600px]:[top:56px] max-[600px]:[font-size:2.1rem]`,
  wallpaper: `tw-components-landing-nfc-demo-wallpaper [position:absolute] [inset:5px] [overflow:hidden] [border-radius:31px] [background:radial-gradient(circle_at_68%_20%,_#1f5da8,_transparent_34%),_linear-gradient(160deg,_#08182b,_#03070d_72%)] max-[600px]:[border-radius:25px]`,
} as const

export default styles
