/**
 * Tailwind utilities for reusable experience artwork.
 * The semantic hook at the start of each value scopes arbitrary descendant variants.
 */
const styles = {
  artwork: `tw-components-artwork-artwork-artwork [--art-scale:1] [position:relative] [min-height:calc(162px_*_var(--art-scale))] [overflow:hidden] [border:1px_solid_var(--experience-border)] [border-radius:calc(22px_*_var(--art-scale))] [background:var(--experience-surface)]`,
  barber: `tw-components-artwork-artwork-barber [background:#171b20]`,
  barberLines: `tw-components-artwork-artwork-barberLines [position:absolute] [inset:-35%_-10%] [transform:rotate(-15deg)] [background:repeating-linear-gradient(_90deg,_transparent_0_calc(20px_*_var(--art-scale)),_rgb(201_166_107_/_13%)_calc(21px_*_var(--art-scale))_calc(22px_*_var(--art-scale))_)]`,
  barberMark: `tw-components-artwork-artwork-barberMark [position:absolute] [right:calc(-8px_*_var(--art-scale))] [bottom:calc(-32px_*_var(--art-scale))] [color:rgb(201_166_107_/_12%)] [font-family:Georgia,_serif] [font-size:calc(7.2rem_*_var(--art-scale))] [font-weight:900]`,
  copy: `tw-components-artwork-artwork-copy [position:relative] [z-index:3] [max-width:72%] [padding:calc(22px_*_var(--art-scale))_calc(18px_*_var(--art-scale))] [&_small]:[display:block] [&_b]:[display:block] [&_span]:[display:block] [&_small]:[color:var(--experience-accent)] [&_small]:[font-size:calc(0.45rem_*_var(--art-scale))] [&_small]:[font-weight:900] [&_small]:[letter-spacing:0.12em] [&_b]:[margin-top:calc(12px_*_var(--art-scale))] [&_b]:[font-size:calc(1.12rem_*_var(--art-scale))] [&_b]:[letter-spacing:-0.04em] [&_b]:[line-height:1.05] [&_span]:[margin-top:calc(9px_*_var(--art-scale))] [&_span]:[color:var(--experience-muted)] [&_span]:[font-size:calc(0.56rem_*_var(--art-scale))] [&_span]:[line-height:1.45]`,
  plate: `tw-components-artwork-artwork-plate [position:absolute] [right:calc(-24px_*_var(--art-scale))] [bottom:calc(-23px_*_var(--art-scale))] [width:calc(138px_*_var(--art-scale))] [height:calc(138px_*_var(--art-scale))] [transform:rotate(-8deg)] [border:calc(16px_*_var(--art-scale))_solid_#f9efe1] [border-radius:50%] [background:radial-gradient(_circle_at_45%_42%,_#d46b45_0_18%,_#6e8b48_19%_30%,_#ead29c_31%_58%,_#8a4c32_59%_65%,_#f7e8d6_66%_)] [box-shadow:0_calc(14px_*_var(--art-scale))_calc(32px_*_var(--art-scale))_rgb(74_42_25_/_20%)] [&::after]:[position:absolute] [&::after]:[right:calc(21px_*_var(--art-scale))] [&::after]:[bottom:calc(18px_*_var(--art-scale))] [&::after]:[display:grid] [&::after]:[width:calc(28px_*_var(--art-scale))] [&::after]:[height:calc(28px_*_var(--art-scale))] [&::after]:[place-items:center] [&::after]:[border-radius:50%] [&::after]:[background:#3c2118] [&::after]:[color:white] [&::after]:[content:'12'] [&::after]:[font-size:calc(0.5rem_*_var(--art-scale))] [&::after]:[font-weight:900]`,
  restaurant: `tw-components-artwork-artwork-restaurant [background:linear-gradient(140deg,_#fff8eb,_#ead1b7)]`,
  service: `tw-components-artwork-artwork-service [background:linear-gradient(140deg,_#f8fffe,_#d9efec)]`,
  serviceGrid: `tw-components-artwork-artwork-serviceGrid [position:absolute] [inset:0] [opacity:0.45] [background-image:linear-gradient(rgb(22_133_127_/_10%)_1px,_transparent_1px),_linear-gradient(90deg,_rgb(22_133_127_/_10%)_1px,_transparent_1px)] [background-size:calc(18px_*_var(--art-scale))_calc(18px_*_var(--art-scale))]`,
  serviceUi: `tw-components-artwork-artwork-serviceUi [position:absolute] [right:calc(18px_*_var(--art-scale))] [bottom:calc(18px_*_var(--art-scale))] [display:grid] [width:calc(72px_*_var(--art-scale))] [gap:calc(6px_*_var(--art-scale))] [padding:calc(11px_*_var(--art-scale))] [border:1px_solid_#b9dbd7] [border-radius:calc(14px_*_var(--art-scale))] [background:rgb(255_255_255_/_78%)] [box-shadow:0_calc(12px_*_var(--art-scale))_calc(26px_*_var(--art-scale))_rgb(17_59_58_/_12%)] [&_i]:[height:calc(5px_*_var(--art-scale))] [&_i]:[border-radius:999px] [&_i]:[background:#16857f] [&_i:nth-child(2)]:[width:70%] [&_i:nth-child(3)]:[width:45%]`,
  store: `tw-components-artwork-artwork-store [background:linear-gradient(140deg,_#fff,_#f1dfef)]`,
  storeEdition: `tw-components-artwork-artwork-storeEdition [position:absolute] [top:calc(-34px_*_var(--art-scale))] [right:calc(-3px_*_var(--art-scale))] [color:rgb(166_63_131_/_10%)] [font-family:Georgia,_serif] [font-size:calc(9rem_*_var(--art-scale))] [line-height:1]`,
  swatches: `tw-components-artwork-artwork-swatches [position:absolute] [right:calc(18px_*_var(--art-scale))] [bottom:calc(17px_*_var(--art-scale))] [display:flex] [gap:calc(5px_*_var(--art-scale))] [&_i]:[width:calc(17px_*_var(--art-scale))] [&_i]:[height:calc(38px_*_var(--art-scale))] [&_i]:[transform:skew(-8deg)] [&_i]:[background:#a63f83] [&_i:nth-child(2)]:[background:#d3a5ca] [&_i:nth-child(3)]:[background:#302034]`,
} as const

export default styles
